# Other Popular Machine Learning Methods

In [1]:
# mount gdrive with this code
from google.colab import drive
drive.mount('/content/drive')

saveFilePath = '/content/drive/My Drive/DataScience_Python_LinkedIn/MyCreatedFiles/'

Mounted at /content/drive


In [3]:
base_address = '/content/drive/My Drive/DataScience_Python_LinkedIn/Data/'

In [17]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

from pandas import Series, DataFrame

from pylab import rcParams

from sklearn.preprocessing import scale
import sklearn.metrics as sm
from sklearn.metrics import confusion_matrix, classification_report

from sklearn.decomposition import FactorAnalysis

from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

import seaborn as sb
sb.set_style('whitegrid')
from collections import Counter

In [28]:
import scipy
import urllib
from sklearn import neighbors
from sklearn import preprocessing
from sklearn import metrics

## Association Rules Models with Apriori

In [ ]:
!pip install mlxtend

In [5]:
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [6]:
address = base_address + 'groceries.csv'
data = pd.read_csv(address)

In [7]:
data.head()

1                    2               3  \
0      citrus fruit  semi-finished bread       margarine   
1    tropical fruit               yogurt          coffee   
2        whole milk                  NaN             NaN   
3         pip fruit               yogurt   cream cheese    
4  other vegetables           whole milk  condensed milk   

                          4    5    6    7    8    9  
0               ready soups  NaN  NaN  NaN  NaN  NaN  
1                       NaN  NaN  NaN  NaN  NaN  NaN  
2                       NaN  NaN  NaN  NaN  NaN  NaN  
3              meat spreads  NaN  NaN  NaN  NaN  NaN  
4  long life bakery product  NaN  NaN  NaN  NaN  NaN

### Data Conversion

In [8]:
basket_sets = pd.get_dummies(data)
basket_sets.head()

1_Instant food products  1_UHT-milk  1_artif. sweetener  1_baby cosmetics  \
0                        0           0                   0                 0   
1                        0           0                   0                 0   
2                        0           0                   0                 0   
3                        0           0                   0                 0   
4                        0           0                   0                 0   

   1_bags  1_baking powder  1_bathroom cleaner  1_beef  1_berries  \
0       0                0                   0       0          0   
1       0                0                   0       0          0   
2       0                0                   0       0          0   
3       0                0                   0       0          0   
4       0                0                   0       0          0   

   1_beverages  ...  9_sweet spreads  9_tea  9_vinegar  9_waffles  \
0            0  ...                0      0          0          0   
1            0  ...                0      0          0          0   
2            0  ...                0      0          0          0   
3            0  ...                0      0          0          0   
4            0  ...                0      0          0          0   

   9_whipped/sour cream  9_white bread  9_white wine  9_whole milk  9_yogurt  \
0                     0              0             0             0         0   
1                     0              0             0             0         0   
2                     0              0             0             0         0   
3                     0              0             0             0         0   
4                     0              0             0             0         0   

   9_zwieback  
0           0  
1           0  
2           0  
3           0  
4           0  

[5 rows x 1113 columns]

In [ ]:
apriori(basket_sets, min_support=0.02)

In [10]:
apriori(basket_sets, min_support=0.02, use_colnames=True)

support                            itemsets
0   0.030421                            (1_beef)
1   0.034951                     (1_canned beer)
2   0.029126                         (1_chicken)
3   0.049191                    (1_citrus fruit)
4   0.064401                     (1_frankfurter)
5   0.044660                (1_other vegetables)
6   0.024272                       (1_pip fruit)
7   0.040453                            (1_pork)
8   0.038835                      (1_rolls/buns)
9   0.033981                 (1_root vegetables)
10  0.076052                         (1_sausage)
11  0.028803                            (1_soda)
12  0.044984                  (1_tropical fruit)
13  0.073463                      (1_whole milk)
14  0.022977                          (1_yogurt)
15  0.028803                    (2_citrus fruit)
16  0.058900                (2_other vegetables)
17  0.022977                       (2_pip fruit)
18  0.040129                      (2_rolls/buns)
19  0.036893                 (2_root vegetables)
20  0.031068                            (2_soda)
21  0.034628                  (2_tropical fruit)
22  0.062136                      (2_whole milk)
23  0.028479                          (2_yogurt)
24  0.045955                (3_other vegetables)
25  0.033010                      (3_rolls/buns)
26  0.024272                            (3_soda)
27  0.057929                      (3_whole milk)
28  0.023301                          (3_yogurt)
29  0.020712                (4_other vegetables)
30  0.024595                      (4_rolls/buns)
31  0.024272                            (4_soda)
32  0.033333                      (4_whole milk)
33  0.023301                          (4_yogurt)
34  0.020065                      (5_rolls/buns)
35  0.021036  (2_other vegetables, 3_whole milk)

In [11]:
df = basket_sets

frequent_itemsets = apriori(basket_sets, min_support=0.002, use_colnames=True)

frequent_itemsets['length'] = frequent_itemsets['itemsets'].apply(lambda x: len(x))
frequent_itemsets

support                                           itemsets  length
0    0.006472                                       (1_UHT-milk)       1
1    0.030421                                           (1_beef)       1
2    0.011974                                        (1_berries)       1
3    0.008414                                      (1_beverages)       1
4    0.014887                                   (1_bottled beer)       1
..        ...                                                ...     ...
844  0.002265    (6_whole milk, 5_other vegetables, 3_pip fruit)       3
845  0.002589  (3_root vegetables, 5_whole milk, 4_other vege...       3
846  0.002913                   (4_curd, 5_yogurt, 3_whole milk)       3
847  0.003236  (4_root vegetables, 6_whole milk, 5_other vege...       3
848  0.002265       (6_whole milk, 7_butter, 5_other vegetables)       3

[849 rows x 3 columns]

In [12]:
frequent_itemsets[frequent_itemsets['length'] >= 3]

support                                           itemsets  length
820  0.002589    (2_root vegetables, 3_other vegetables, 1_beef)       3
821  0.002589      (2_other vegetables, 1_chicken, 3_whole milk)       3
822  0.002589  (2_other vegetables, 1_citrus fruit, 3_whole m...       3
823  0.003236    (2_tropical fruit, 1_citrus fruit, 3_pip fruit)       3
824  0.002589  (1_citrus fruit, 3_other vegetables, 4_whole m...       3
825  0.002265  (1_frankfurter, 6_whole milk, 5_other vegetables)       3
826  0.002265         (3_other vegetables, 4_whole milk, 1_pork)       3
827  0.003560  (2_other vegetables, 1_root vegetables, 3_whol...       3
828  0.002589                  (3_soda, 2_rolls/buns, 1_sausage)       3
829  0.002265      (3_other vegetables, 4_whole milk, 1_sausage)       3
830  0.002265      (5_whole milk, 4_other vegetables, 1_sausage)       3
831  0.002913  (2_other vegetables, 1_tropical fruit, 3_whole...       3
832  0.002265  (5_whole milk, 4_other vegetables, 2_citrus fr...       3
833  0.002265       (2_other vegetables, 4_butter, 3_whole milk)       3
834  0.003560         (2_other vegetables, 4_curd, 3_whole milk)       3
835  0.003883       (2_other vegetables, 4_yogurt, 3_whole milk)       3
836  0.002265   (2_other vegetables, 6_rolls/buns, 3_whole milk)       3
837  0.003236    (3_other vegetables, 4_whole milk, 2_pip fruit)       3
838  0.005825  (2_root vegetables, 3_other vegetables, 4_whol...       3
839  0.002265  (2_tropical fruit, 3_pip fruit, 4_other vegeta...       3
840  0.003560       (5_butter, 3_other vegetables, 4_whole milk)       3
841  0.002913       (5_yogurt, 3_other vegetables, 4_whole milk)       3
842  0.003560       (6_yogurt, 3_other vegetables, 4_whole milk)       3
843  0.002265  (4_root vegetables, 5_other vegetables, 3_pip ...       3
844  0.002265    (6_whole milk, 5_other vegetables, 3_pip fruit)       3
845  0.002589  (3_root vegetables, 5_whole milk, 4_other vege...       3
846  0.002913                   (4_curd, 5_yogurt, 3_whole milk)       3
847  0.003236  (4_root vegetables, 6_whole milk, 5_other vege...       3
848  0.002265       (6_whole milk, 7_butter, 5_other vegetables)       3

### Association Rules

In [13]:
# Confidence

rules = association_rules(frequent_itemsets, metric='confidence', min_threshold=0.5)
rules.head()

antecedents      consequents  antecedent support  consequent support  \
0  (2_sausage)  (1_frankfurter)            0.011327            0.064401   
1   (7_pastry)  (1_frankfurter)            0.005178            0.064401   
2      (2_ham)      (1_sausage)            0.007120            0.076052   
3     (2_meat)      (1_sausage)            0.006796            0.076052   
4     (3_beef)      (1_sausage)            0.004854            0.076052   

    support  confidence       lift  leverage  conviction  
0  0.011327    1.000000  15.527638  0.010597         inf  
1  0.002589    0.500000   7.763819  0.002256    1.871197  
2  0.004531    0.636364   8.367505  0.003989    2.540858  
3  0.004854    0.714286   9.392097  0.004338    3.233819  
4  0.002589    0.533333   7.012766  0.002220    1.979889

In [14]:
# Lift

rules = association_rules(frequent_itemsets, metric='lift', min_threshold=1)
rules.head()

antecedents           consequents  antecedent support  \
0              (1_beef)      (2_citrus fruit)            0.030421   
1      (2_citrus fruit)              (1_beef)            0.028803   
2  (2_other vegetables)              (1_beef)            0.058900   
3              (1_beef)  (2_other vegetables)            0.030421   
4   (2_root vegetables)              (1_beef)            0.036893   

   consequent support   support  confidence      lift  leverage  conviction  
0            0.028803  0.005502    0.180851  6.278986  0.004625    1.185618  
1            0.030421  0.005502    0.191011  6.278986  0.004625    1.198508  
2            0.030421  0.003236    0.054945  1.806173  0.001444    1.025950  
3            0.058900  0.003236    0.106383  1.806173  0.001444    1.053136  
4            0.030421  0.005502    0.149123  4.902016  0.004379    1.139506

In [15]:
# Lift and Confidence

rules[(rules['lift'] >= 5) & (rules['confidence'] >= 0.5)]

antecedents  \
93                               (2_sausage)   
137                               (7_pastry)   
238                                  (2_ham)   
242                                 (2_meat)   
258                                 (3_beef)   
..                                       ...   
958        (4_root vegetables, 6_whole milk)   
959  (4_root vegetables, 5_other vegetables)   
964                 (6_whole milk, 7_butter)   
966           (7_butter, 5_other vegetables)   
968                               (7_butter)   

                            consequents  antecedent support  \
93                      (1_frankfurter)            0.011327   
137                     (1_frankfurter)            0.005178   
238                         (1_sausage)            0.007120   
242                         (1_sausage)            0.006796   
258                         (1_sausage)            0.004854   
..                                  ...                 ...   
958                (5_other vegetables)            0.003883   
959                      (6_whole milk)            0.005178   
964                (5_other vegetables)            0.002913   
966                      (6_whole milk)            0.002589   
968  (6_whole milk, 5_other vegetables)            0.004207   

     consequent support   support  confidence       lift  leverage  conviction  
93             0.064401  0.011327    1.000000  15.527638  0.010597         inf  
137            0.064401  0.002589    0.500000   7.763819  0.002256    1.871197  
238            0.076052  0.004531    0.636364   8.367505  0.003989    2.540858  
242            0.076052  0.004854    0.714286   9.392097  0.004338    3.233819  
258            0.076052  0.002589    0.533333   7.012766  0.002220    1.979889  
..                  ...       ...         ...        ...       ...         ...  
958            0.012621  0.003236    0.833333  66.025641  0.003187    5.924272  
959            0.009385  0.003236    0.625000  66.594828  0.003188    2.641640  
964            0.012621  0.002265    0.777778  61.623932  0.002229    4.443204  
966            0.009385  0.002265    0.875000  93.232759  0.002241    7.924919  
968            0.007443  0.002265    0.538462  72.341137  0.002234    2.150539  

[76 rows x 9 columns]

## Neural Networks with a Perceptron

In [18]:
from sklearn.linear_model import Perceptron

In [19]:
iris = datasets.load_iris()

X = iris.data
y = iris.target

In [20]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [21]:
standardize = StandardScaler()

standardized_x_test = standardize.fit_transform(x_test)
standardized_x_train = standardize.fit_transform(x_train)

In [22]:
standardized_x_test[0:10,]

array([[-0.73822681,  0.84916742, -1.43434251, -1.18107341],
       [ 0.0820252 , -1.88029929,  0.01742116, -0.36025019],
       [-0.60151814,  2.66881189, -1.49241306, -1.45468115],
       [ 1.03898588,  0.16680074,  0.24970335,  0.18696529],
       [-1.01164414,  0.84916742, -1.49241306, -1.45468115],
       [ 1.72252922, -0.06065482,  1.06269101,  0.46057303],
       [ 2.40607256, -0.97047705,  1.70146703,  1.41820011],
       [ 1.17569454,  0.3942563 ,  1.12076156,  1.41820011],
       [ 0.4921512 , -0.74302149,  0.54005609,  0.73418077],
       [-0.05468347, -0.06065482,  0.65619718,  0.73418077]])

In [23]:
perceptron = Perceptron(max_iter=50, eta0=0.15, tol=1e-3, random_state=15)
perceptron.fit(standardized_x_train, y_train.ravel())

Perceptron(eta0=0.15, max_iter=50, random_state=15)

In [24]:
y_pred = perceptron.predict(standardized_x_test)

In [25]:
print(y_test)

[0 1 0 1 0 2 2 2 2 2 0 2 0 1 2 2 0 2 1 2 1 1 2 0 1 2 0 1 0 2]


In [26]:
print(y_pred)

[0 1 0 1 0 1 1 2 1 1 0 1 0 1 2 1 0 2 1 2 1 1 1 0 1 1 0 1 0 1]


In [27]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       0.47      1.00      0.64         8
           2       1.00      0.31      0.47        13

    accuracy                           0.70        30
   macro avg       0.82      0.77      0.70        30
weighted avg       0.86      0.70      0.67        30



## Instance-Based learning with KNN

In [29]:
from sklearn.neighbors import KNeighborsClassifier

In [30]:
from ast import increment_lineno
np.set_printoptions(precision=4, suppress=True)
%matplotlib inline
rcParams['figure.figsize'] = 7, 4
plt.style.use('seaborn-whitegrid')

<ipython-input-30-763dea8b7327>:5: MatplotlibDeprecationWarning: The seaborn styles shipped by Matplotlib are deprecated since 3.6, as they no longer correspond to the styles shipped by seaborn. However, they will remain available as 'seaborn-v0_8-<style>'. Alternatively, directly use the seaborn API instead.
  plt.style.use('seaborn-whitegrid')


In [35]:
address = base_address + 'mtcars.csv'

cars = pd.read_csv(address)
cars.columns = ['car_names', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear', 'carb']

X_prime = cars[['mpg', 'disp', 'hp', 'wt']].values
y = cars.iloc[:,9].values

In [36]:
X = preprocessing.scale(X_prime)

In [37]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=17)

### Build and Evaluate Model

In [40]:
clf = neighbors.KNeighborsClassifier()
clf.fit(X_train, y_train)
print(clf)

KNeighborsClassifier()


In [42]:
y_pred = clf.predict(X_test)
y_expect = y_test

print(classification_report(y_expect, y_pred))

              precision    recall  f1-score   support

           0       0.80      1.00      0.89         4
           1       1.00      0.67      0.80         3

    accuracy                           0.86         7
   macro avg       0.90      0.83      0.84         7
weighted avg       0.89      0.86      0.85         7



## Decision Tree models with CART - no Code

## Bayesian models with Naive Bayes

In [43]:
from sklearn.metrics import accuracy_score

from sklearn.naive_bayes import BernoulliNB, GaussianNB, MultinomialNB

In [46]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/spambase/spambase.data"

import urllib.request

raw_data = urllib.request.urlopen(url)
dataset = np.loadtxt(raw_data, delimiter=',')

print(dataset[0])

[  0.      0.64    0.64    0.      0.32    0.      0.      0.      0.
   0.      0.      0.64    0.      0.      0.      0.32    0.      1.29
   1.93    0.      0.96    0.      0.      0.      0.      0.      0.
   0.      0.      0.      0.      0.      0.      0.      0.      0.
   0.      0.      0.      0.      0.      0.      0.      0.      0.
   0.      0.      0.      0.      0.      0.      0.778   0.      0.
   3.756  61.    278.      1.   ]


In [47]:
X = dataset[:, 0:48]

y = dataset[:, -1]

In [48]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=17)

In [50]:
BernNB = BernoulliNB(binarize=True)
BernNB.fit(X_train, y_train)
print(BernNB)

y_expect = y_test
y_pred = BernNB.predict(X_test)
                        
print(accuracy_score(y_expect, y_pred))

BernoulliNB(binarize=True)
0.8577633007600435


In [51]:
MultiNB = MultinomialNB()
MultiNB.fit(X_train, y_train)
print(MultiNB)

y_pred = MultiNB.predict(X_test)
                        
print(accuracy_score(y_expect, y_pred))

MultinomialNB()
0.8816503800217155


In [52]:
GaussNB = GaussianNB()
GaussNB.fit(X_train, y_train)
print(GaussNB)

y_pred = GaussNB.predict(X_test)
                        
print(accuracy_score(y_expect, y_pred))

GaussianNB()
0.8197611292073833


In [53]:
BernNB = BernoulliNB(binarize=0.1)
BernNB.fit(X_train, y_train)
print(BernNB)

y_expect = y_test
y_pred = BernNB.predict(X_test)
                        
print(accuracy_score(y_expect, y_pred))

BernoulliNB(binarize=0.1)
0.9109663409337676


## Ensemble Methods with Random Forest

In [54]:
from sklearn.ensemble import RandomForestClassifier

In [59]:
df = pd.DataFrame(iris.data, columns=iris.feature_names)
y = pd.DataFrame(iris.target)

y.columns = ['labels']

print(df.head())
y[0:5]

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2


labels
0       0
1       0
2       0
3       0
4       0

In [61]:
df.isnull().any()==True

sepal length (cm)    False
sepal width (cm)     False
petal length (cm)    False
petal width (cm)     False
dtype: bool

In [63]:
print(y.labels.value_counts())

0    50
1    50
2    50
Name: labels, dtype: int64


### Prepare Data, Build and Evaluate Model

In [64]:
X_train, X_test, y_train, y_test = train_test_split(df, y, test_size=0.2, random_state=17)

In [65]:
classifier = RandomForestClassifier(n_estimators=200, random_state=0)

y_train_array = np.ravel(y_train)

classifier.fit(X_train, y_train_array)

y_pred = classifier.predict(X_test)

In [66]:
print(metrics.classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         7
           1       0.92      1.00      0.96        11
           2       1.00      0.92      0.96        12

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30



In [68]:
y_test_array = np.ravel(y_test)
print(y_test_array)

[0 1 2 1 2 2 1 2 1 2 2 0 1 0 2 0 0 2 2 2 2 0 2 1 1 1 1 1 0 1]


In [69]:
print(y_pred)

[0 1 2 1 2 2 1 2 1 2 2 0 1 0 2 0 0 2 2 2 1 0 2 1 1 1 1 1 0 1]
