## Comparison, Masking and Boolean Logic

This notebooks explains how we can use NumPy to manipulate array values based on a criterion, we'll talk about the following:

1. How to use comparison operators as element-wise universal functions.
2. How to use boolean arrays with composite conditions.
3. How to use boolean arrays as masks to extract the required values.

In [ ]:
import numpy as np

In [ ]:
##defining an array
arr = np.array([10,20,30,40,50])

arr >= 20

array([False,  True,  True,  True,  True])

In [ ]:
arr == 30

array([False, False,  True, False, False])

In [ ]:
##equivalent ufunc for the comparison operator
np.greater(arr, 30)

array([False, False, False,  True,  True])

### Boolean Arrays

In [ ]:
##creating a 2D array of random integers with values < 10
arr = np.random.randint(10, size=(3,4))
arr

array([[6, 7, 0, 4],
       [4, 2, 9, 8],
       [0, 1, 1, 7]])

In [ ]:
##counting number of values that are greater than 5 using np.sum()
np.sum(arr > 5)

5

In [ ]:
##counting number of values that are greater than 5 in each row
np.sum(arr > 5, axis=1)

array([2, 2, 1])

In [ ]:
##checking if any or all value are above or below a threshold
np.any(arr > 5)

True

In [ ]:
##check if all values are > 5
np.all(arr > 5)

False

## Boolean Operators to handle multiple conditions

In [ ]:
##math test scores of students in a class
test_scores = np.random.randint(100, size=(30))
test_scores


array([69, 26, 55, 92, 31, 52, 78, 23, 55, 41, 80, 19, 23, 13, 90, 11, 46,
       13,  3, 13, 17, 11, 65, 48, 92,  4, 47, 33, 83, 19])

In [ ]:
##number of students who scored more than 50 but less than 75

np.sum((test_scores > 50) & (test_scores < 75))

5

In [ ]:
##extracting all the indices which meet the condition
np.where((test_scores > 50) & (test_scores < 75))

(array([ 0,  2,  5,  8, 22]),)

## Masking

Using Boolean arrays as masks

In [ ]:
##Extracting all the elements(values) that adhere to the mask
mask = test_scores > 75

In [ ]:
test_scores[mask]

array([92, 78, 80, 90, 92, 83])