## Broadcasting

This notebooks explains broadcasting, a widely used operation in data science. 


In [ ]:
import numpy as np

### Broadcasting 

A functionality that states a set of rules to apply binary universal functions(addition, subtraction, multiplication, etc.) on arrays of varied sizes.

In [ ]:
##defining 2 arrays and adding them as vectors


a = np.array([3,4,5])
b = np.array([7,8,9])

a+b


array([10, 12, 14])

In [ ]:
##adding a scalar to an array 

a + 10

##interpretation: a + [10,10,10]

array([13, 14, 15])

In [ ]:
##creating an array of 1s.
ones = np.ones((3,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
##adding a 1D array to a 2D array;
ones + a

array([[4., 5., 6.],
       [4., 5., 6.],
       [4., 5., 6.]])

### Rules of Broadcasting

Broadcasting in NumPy follows a strict set of rules to determine the interaction between the two arrays:

Rule 1: If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.

Rule 2: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.

Rule 3: If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

In [ ]:
##example of rule 1
a = np.ones((2, 3))
b = np.arange(3)

print("a: \n", a)
print("b: \n", b)
print("a+b: \n", a+b)

a: 
 [[1. 1. 1.]
 [1. 1. 1.]]
b: 
 [0 1 2]
a+b: 
 [[1. 2. 3.]
 [1. 2. 3.]]


Originally,

a.shape = (2, 3)

b.shape = (3,)

=========After applying rule 1: =========

a.shape -> (2, 3)

b.shape -> (1, 3)

=========After applying rule 2: =========

a.shape -> (2, 3)

b.shape -> (2, 3)

In [ ]:
##example of rule 2
a = np.arange(3).reshape((3,1))
b = np.arange(3)
a+b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

Originally,

a.shape = (3, 1)

b.shape = (3,)

=========After applying rule 1: =========

a.shape -> (3, 1)

b.shape -> (1, 3)

=========After applying rule 2: =========

a.shape -> (3, 3)

b.shape -> (3, 3)

In [ ]:
##example of rule 3
a = np.ones((3,2))
b = np.arange(3)
a + b

ValueError: ignored

Originally,

a.shape = (3, 2)

b.shape = (3,)

=========After applying rule 1: =========

a.shape -> (3, 2)

b.shape -> (1, 3)

=========After applying rule 2: =========

a.shape -> (3, 2)

b.shape -> (3, 3)